using System.Windows.Input;

namespace MR.Gestures;

public partial class GestureHandler
{
	// Most of this class will be generated by Controls.tt and can be found at the end of Controls.cs.

	IGestureAwareControl Element;

	public GestureHandler(IGestureAwareControl element)
	{
		Element = element;
	}

	private void RaiseEvent<T>(EventHandler<T> handler, T args) where T : BaseGestureEventArgs
	{
		args.Sender = Element;

		if (handler != null)
			handler(Element, args);
	}

	private void ExecuteCommand(ICommand command, object parameter, BaseGestureEventArgs args)
	{
		if (command != null)
		{
			args.Sender = Element;
			parameter = parameter ?? args;      // use args if parameter == null

			if (command.CanExecute(parameter))
				command.Execute(parameter);
		}
	}
}
